services:
  fastapi:
    hostname: fastapi
    container_name: fastapi
    build:
      context: .
      dockerfile: dockerfile_sumo_fastapi
    environment:
      - SUMO_HOME=/usr/share/sumo
    ports:
      - "8001:8000"
    stdin_open: true
    tty: true
    volumes:
      - ./output:/tmp/output
    networks:
      - sumo_network
  
  nginx_server:
    hostname: nginx
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfile_nginx
    ports:
      - "82:80"
    # depends_on:
    #   - fastapi
    networks:
      - sumo_network

  duckdb:
    hostname: duckdb
    container_name: duckdb
    build:
      context: .
      dockerfile: dockerfile_duckdb
    environment:
      POSTGRES_DB: sumo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgis:/var/lib/postgresql/data
      - ./output:/tmp/parquet_files
    networks:
      - sumo_network

  postrest:
    image: postgrest/postgrest
    hostname: postrest
    container_name: postrest
    ports:
      - "3000:3000"
    environment:
      PGRST_SERVER_HOST: 0.0.0.0
      # URI de conexión (usamos el nombre del servicio 'db')
      PGRST_DB_URI: postgres://admin:admin@duckdb:5432/sumo
      # Esquema que expondrá la API
      PGRST_DB_SCHEMA: api
      # Rol para usuarios no autenticados
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - duckdb
    networks:
      - sumo_network

  swagger:
    hostname: swagger
    container_name: swagger
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
    networks:
      - sumo_network

networks:
  sumo_network:
    driver: bridge
    