services:
  # fastapi:
  #   hostname: fastapi
  #   container_name: fastapi
  #   build:
  #     context: .
  #     dockerfile: dockerfile_sumo_fastapi
  #   environment:
  #     - SUMO_HOME=/usr/share/sumo
  #   ports:
  #     - "8001:8000"
  #   stdin_open: true
  #   tty: true
  #   # volumes:
  #   #   - ./temp/output:/tmp/output
  #   networks:
  #     - sumo_network
  
  nginx_server:
    hostname: nginx
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfile_nginx
    ports:
      - "82:80"
    # depends_on:
    #   - fastapi
    networks:
      - sumo_network

  duckdb:
    hostname: duckdb
    container_name: duckdb
    build:
      context: .
      dockerfile: dockerfile_duckdb
    environment:
      POSTGRES_DB: sumo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./output:/tmp/parquet_files

networks:
  sumo_network:
    driver: bridge
    