FROM ubuntu:jammy

ENV SUMO_HOME=/usr/share/sumo
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONPATH="$SUMO_HOME/tools"


RUN echo "Actualizando repositorios de dependencias"
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak
RUN sed -i 's/http:\/\/archive.ubuntu.com/http:\/\/es.archive.ubuntu.com/g' /etc/apt/sources.list
RUN sed -i 's/http:\/\/security.ubuntu.com/http:\/\/es.archive.ubuntu.com/g' /etc/apt/sources.list

RUN echo "Actualizado dependencias"
RUN apt-get -y update
RUN echo "instalando software-properties-common"
RUN apt-get -y install software-properties-common
RUN echo "Añadiendo repositorio sumo"
RUN add-apt-repository ppa:sumo/stable

RUN echo "Instalando SUMO instalado correctamente"
RUN apt-get -y update
RUN apt-get -y install sumo sumo-doc sumo-tools
RUN echo "SUMO instalado correctamente"

RUN echo "Instalando dependencias de python"
RUN apt-get install -y python3 python3-pip

RUN mkdir -p /tmp/output

COPY ./red_carreteras/zona-sancho-el-fuerte.net.xml /tmp/zona-sancho-el-fuerte.net.xml
COPY ./red_carreteras/zona-sancho-el-fuerte.rou.xml /tmp/zona-sancho-el-fuerte.rou.xml

COPY ./red_carreteras/pamplona.net.xml /tmp/pamplona.net.xml
COPY ./red_carreteras/additional.add.xml /tmp/additional.add.xml
COPY ./red_carreteras/closedEdge.add.xml /tmp/closedEdge.add.xml

COPY ./red_carreteras/mapa.rou.xml /tmp/mapa.rou.xml
COPY ./red_carreteras/vehicles.add.xml /tmp/vehicles.add.xml
COPY ./red_carreteras/simulation.sumocfg /tmp/simulation.sumocfg

#COPY ./output/edgeEmissions.parquet /tmp/edgeEmissions.parquet
#COPY ./output/edgeTraffic.parquet /tmp/edgeTraffic.parquet

RUN echo "Archivos copiandos de SUMO"

RUN echo "Instalando Fastapi"
RUN pip install "fastapi[standard]"
WORKDIR /code
COPY ./fastapi/requirements.txt /code/requirements.txt
RUN pip install -r /code/requirements.txt
COPY ./fastapi/ /code/app

CMD ["fastapi", "run", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]