FROM nginx:latest
WORKDIR /usr/share/nginx/html
COPY nginx/proxy_inverso.conf /etc/nginx/conf.d/default.conf
RUN echo "Copiando fichero de WEB"
COPY web/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]